server:
  port: 8082
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8080/eureka/
    should-unregister-on-shutdown: true
spring:
  application:
    name: eureka-client